/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JogoWorms.java
 *
 * Created on 04/12/2010, 15:41:46
 */
package Visual;

import javax.swing.JOptionPane;

public class JogoWorms extends javax.swing.JFrame {

    /** Creates new form JogoWorms */
    public JogoWorms() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Niveis = new javax.swing.ButtonGroup();
        LabelJogoDaMemoriaWorms = new javax.swing.JLabel();
        LabelNomeWorms = new javax.swing.JLabel();
        LabelTitulo = new javax.swing.JLabel();
        NivelFacil = new javax.swing.JRadioButton();
        NivelAvancado = new javax.swing.JRadioButton();
        NivelMedio = new javax.swing.JRadioButton();
        BotaoOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        SubMenuArquivo_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Memória Worms ");
        setResizable(false);

        LabelJogoDaMemoriaWorms.setFont(new java.awt.Font("Century Gothic", 0, 36));
        LabelJogoDaMemoriaWorms.setText("Jogo da Memória  ");

        LabelNomeWorms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WormsNome.png"))); // NOI18N

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24));
        LabelTitulo.setText("Selecione a dificuldade do seu jogo:");

        Niveis.add(NivelFacil);
        NivelFacil.setFont(new java.awt.Font("Tahoma", 0, 18));
        NivelFacil.setText("Fácil 4x4");

        Niveis.add(NivelAvancado);
        NivelAvancado.setFont(new java.awt.Font("Tahoma", 0, 18));
        NivelAvancado.setText("Avançado 8x8");

        Niveis.add(NivelMedio);
        NivelMedio.setFont(new java.awt.Font("Tahoma", 0, 18));
        NivelMedio.setText("Médio 6x6");

        BotaoOK.setText("Iniciar Jogo");
        Niveis.add(BotaoOK);
        BotaoOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoOKMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TelaInicial.png"))); // NOI18N

        MenuArquivo.setText("Arquivo");

        SubMenuArquivo_Sair.setText("Sair");
        SubMenuArquivo_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuArquivo_SairActionPerformed(evt);
            }
        });
        MenuArquivo.add(SubMenuArquivo_Sair);

        BarraMenu.add(MenuArquivo);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NivelAvancado)
                    .addComponent(NivelMedio)
                    .addComponent(NivelFacil)
                    .addComponent(BotaoOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJogoDaMemoriaWorms)
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LabelNomeWorms)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(LabelTitulo)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJogoDaMemoriaWorms)
                .addGap(38, 38, 38)
                .addComponent(LabelNomeWorms, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(LabelTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(NivelFacil)
                        .addGap(11, 11, 11)
                        .addComponent(NivelMedio)
                        .addGap(15, 15, 15)
                        .addComponent(NivelAvancado)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOKMouseClicked
        if (NivelFacil.isSelected() == true)//Verifica se ao ter clicado em OK, se o RadioButton - Nivel Facil está selecionado
        {

            JogoNivelFacil newjogo = new JogoNivelFacil();// Cria um objeto do tipo JogoNivelFacil
            newjogo.setVisible(true);//Inicia o Jogo no Nível Fácil (torna a sua visibilidade verdadeira)
            JogoWorms.super.setVisible(false);//Torna a visibilidade do JFrame JogoWorms falsa
        } else if (NivelMedio.isSelected() == true)//Verifica se ao ter clicado em OK, se o RadioButton - Nivel Medio está selecionado
        {
            JogoNivelMedio newjogo = new JogoNivelMedio();// Cria um objeto do tipo JogoNivelMedio
            newjogo.setVisible(true);//Inicia o Jogo no Nível Medio (torna a sua visibilidade verdadeira)
            JogoWorms.super.setVisible(false);//Torna a visibilidade do JFrame JogoWorms falsa
        } else if (NivelAvancado.isSelected() == true)//Verifica se ao ter clicado em OK, se o RadioButton - Nivel Avançado está selecionado
        {
            JogoNivelAvancado newjogo = new JogoNivelAvancado();// Cria um objeto do tipo JogoNivelAvancado
            newjogo.setVisible(true);//Inicia o Jogo no Nível Avançado (torna a sua visibilidade verdadeira)
            JogoWorms.super.setVisible(false);//Torna a visibilidade do JFrame JogoWorms falsa
        } else {//Caso nenhuma das opções estejam marcadas
            JOptionPane.showMessageDialog(null, "Selecione um dos níveis!");
        }



    }//GEN-LAST:event_BotaoOKMouseClicked

    private void SubMenuArquivo_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuArquivo_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SubMenuArquivo_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JogoWorms().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JButton BotaoOK;
    private javax.swing.JLabel LabelJogoDaMemoriaWorms;
    private javax.swing.JLabel LabelNomeWorms;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JMenu MenuArquivo;
    private javax.swing.ButtonGroup Niveis;
    private javax.swing.JRadioButton NivelAvancado;
    private javax.swing.JRadioButton NivelFacil;
    private javax.swing.JRadioButton NivelMedio;
    private javax.swing.JMenuItem SubMenuArquivo_Sair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
