/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JogoNivelFacil.java
 *
 * Created on 04/12/2010, 23:30:33
 */
package Visual;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import visual.CartaNivelFacil;


public class JogoNivelFacil extends javax.swing.JFrame {

    ArrayList<CartaNivelFacil> cartas = new ArrayList<CartaNivelFacil>();

    /** Creates new form JogoNivelFacil */
    public JogoNivelFacil() {
        initComponents();


        /*Criando as cartas*/
        CartaNivelFacil carta1 = new CartaNivelFacil("/Imagens/IMAGEM1.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta2 = new CartaNivelFacil("/Imagens/IMAGEM1.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta3 = new CartaNivelFacil("/Imagens/IMAGEM2.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta4 = new CartaNivelFacil("/Imagens/IMAGEM2.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta6 = new CartaNivelFacil("/Imagens/IMAGEM3.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta7 = new CartaNivelFacil("/Imagens/IMAGEM3.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta8 = new CartaNivelFacil("/Imagens/IMAGEM4.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta9 = new CartaNivelFacil("/Imagens/IMAGEM4.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta10 = new CartaNivelFacil("/Imagens/IMAGEM5.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta11 = new CartaNivelFacil("/Imagens/IMAGEM5.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta12 = new CartaNivelFacil("/Imagens/IMAGEM6.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta13 = new CartaNivelFacil("/Imagens/IMAGEM6.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta14 = new CartaNivelFacil("/Imagens/IMAGEM7.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta5 = new CartaNivelFacil("/Imagens/IMAGEM7.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta15 = new CartaNivelFacil("/Imagens/IMAGEM8.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        CartaNivelFacil carta16 = new CartaNivelFacil("/Imagens/IMAGEM8.png", LabelPontuacao, LabelQuantDeCartasViradas2, SubMenuDeJogo_NovoJogo);
        /*Adicionando as cartas no ArrayList*/
        cartas.add(carta1);
        cartas.add(carta2);
        cartas.add(carta3);
        cartas.add(carta4);
        cartas.add(carta5);
        cartas.add(carta6);
        cartas.add(carta7);
        cartas.add(carta8);
        cartas.add(carta9);
        cartas.add(carta10);
        cartas.add(carta11);
        cartas.add(carta12);
        cartas.add(carta13);
        cartas.add(carta14);
        cartas.add(carta15);
        cartas.add(carta16);
        /*Definindo os pares das cartas em relação da primeira para a segunda*/
        carta1.setPar(carta2);
        carta3.setPar(carta4);
        carta6.setPar(carta7);
        carta8.setPar(carta9);
        carta10.setPar(carta11);
        carta12.setPar(carta13);
        carta14.setPar(carta5);
        carta15.setPar(carta16);
        /*Definindo os pares das cartas em relação da segunda para a primeira*/
        carta2.setPar(carta1);
        carta4.setPar(carta3);
        carta7.setPar(carta6);
        carta9.setPar(carta8);
        carta11.setPar(carta10);
        carta13.setPar(carta12);
        carta5.setPar(carta14);
        carta16.setPar(carta15);



        Collections.shuffle(cartas);
        for (CartaNivelFacil c : cartas) {
            c.Esconder_Carta();
            PainelPrincipal.add(c);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPontos = new javax.swing.JLabel();
        LabelPontuacao = new javax.swing.JLabel();
        LabelCartasViradas = new javax.swing.JLabel();
        LabelQuantDeCartasViradas2 = new javax.swing.JLabel();
        PainelPrincipal = new javax.swing.JPanel();
        BarraDeMenu = new javax.swing.JMenuBar();
        MenuJogo = new javax.swing.JMenu();
        SubMenuDeJogo_NovoJogo = new javax.swing.JMenuItem();
        SubMenuDeJogo_Opcoes = new javax.swing.JMenuItem();
        SubMenuDeJogo_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Memória Worms - Nível Fácil");
        setResizable(false);

        LabelPontos.setText("Pontos:");

        LabelPontuacao.setText("0");

        LabelCartasViradas.setText("Cartas Viradas:");

        LabelQuantDeCartasViradas2.setText("0");

        PainelPrincipal.setLayout(new java.awt.GridLayout(4, 4));

        MenuJogo.setText("Jogo");

        SubMenuDeJogo_NovoJogo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        SubMenuDeJogo_NovoJogo.setText("Novo Jogo");
        SubMenuDeJogo_NovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuDeJogo_NovoJogoActionPerformed(evt);
            }
        });
        MenuJogo.add(SubMenuDeJogo_NovoJogo);

        SubMenuDeJogo_Opcoes.setText("Opções");
        SubMenuDeJogo_Opcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuDeJogo_OpcoesActionPerformed(evt);
            }
        });
        MenuJogo.add(SubMenuDeJogo_Opcoes);

        SubMenuDeJogo_Sair.setText("Sair");
        SubMenuDeJogo_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuDeJogo_SairActionPerformed(evt);
            }
        });
        MenuJogo.add(SubMenuDeJogo_Sair);

        BarraDeMenu.add(MenuJogo);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelPontos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelPontuacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                        .addComponent(LabelCartasViradas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelQuantDeCartasViradas2)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPontos)
                    .addComponent(LabelPontuacao)
                    .addComponent(LabelCartasViradas)
                    .addComponent(LabelQuantDeCartasViradas2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuDeJogo_NovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuDeJogo_NovoJogoActionPerformed
        JogoNivelFacil newJogo = new JogoNivelFacil();//Cria um objeto do tipo JogoNivelFacil
        newJogo.setVisible(true);//Torna a visibilidade no jogo nivel fácil true
        JogoNivelFacil.super.setVisible(false);//Torna o JFrame JogoNivelFacil com visibilidade false
    }//GEN-LAST:event_SubMenuDeJogo_NovoJogoActionPerformed

    private void SubMenuDeJogo_OpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuDeJogo_OpcoesActionPerformed
        Opcoes op = new Opcoes();//Cria um objeto do tipo Opcoes
        op.setVisible(true);//Torna a visibilidade de opções true
        JogoNivelFacil.super.setVisible(false);//Torna a visibilidade do Frame JogoNivelFacil como false
    }//GEN-LAST:event_SubMenuDeJogo_OpcoesActionPerformed

    private void SubMenuDeJogo_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuDeJogo_SairActionPerformed
        System.exit(0);//Sai do programa
    }//GEN-LAST:event_SubMenuDeJogo_SairActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JLabel LabelCartasViradas;
    private javax.swing.JLabel LabelPontos;
    private javax.swing.JLabel LabelPontuacao;
    private javax.swing.JLabel LabelQuantDeCartasViradas2;
    private javax.swing.JMenu MenuJogo;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JMenuItem SubMenuDeJogo_NovoJogo;
    private javax.swing.JMenuItem SubMenuDeJogo_Opcoes;
    private javax.swing.JMenuItem SubMenuDeJogo_Sair;
    // End of variables declaration//GEN-END:variables
}
